### ISSUE TITLE
Slash commands support

### ISSUE THREAD

**Issue by krisppurg** [ire4ever1190/dimscmd#1]
It could look like this, not too sure about multiple options
```nim
proc foo(bar: string) {.slash_command.} =
    ## Foo some bars
   discard await discord.api.sendMessage(m.channel_id, "Foo be spitting dem bars tho.")
```

**Comment by ire4ever1190** [comment]
It will probably end up being something that.
When you say multiple options I am guessing you are talking about the choices they have for an option?
For them I'll probably handle them with enums
```nim
type Animal = enum
    Dog
    Cat
    Penguin
proc noise(animal: Animal) {.slash_command.} =
    case animal:
        # Make noise
```

Are you currently implementing the web socket code for receiving the events in dimscord?

**Comment by krisppurg** [comment]
Currently writing the structure for the objects for the slash commands, after that restapi, after restapi then testing after testing impl for gateway.

I've started to notice the source files are starting to get huger, so I'm going to split them later.

**Comment by krisppurg** [comment]
As you know, now I have implemented slash commands.

**Comment by ire4ever1190** [comment]
Basic slash command support is added in the latest commit 

the piece of code that is meant to remove commands that the user has removed is not working though, but I am pretty sure that is an issue with me and not with the dimscord lib

**Comment by krisppurg** [comment]
I have made a mistake on the removing application command code as you may have not have known already, it was sending a "GET" request, thanks to `@dannyhpy` for pointing it out on the Dimscord Server

**Comment by krisppurg** [comment]
Also, as you are implementing slash commands, I figured that I am still behind. I will implement stuff like Slash Command Permissions as well as updating the PermissionFlags. Just to inform you. Since I am going to either do a big release.

**Comment by ire4ever1190** [comment]
Sub commands finally finished in latest commits
Haven't added a way to set sub group description because I can't actually find where the sub group is displayed in discord 🤷
