### ISSUE TITLE
Slash command needs description, but addSlash not provide argument

### ISSUE THREAD

**Issue by rikusen0335** [ire4ever1190/dimscmd#10]
## Describe the bug
As reading source, [this line](https://github.com/ire4ever1190/dimscmd/blob/2a50625e6968d7ba8dcf88d3bb9dca5ec99e4676/src/dimscmd.nim#L169) 
 in `addCommand` needs description, but `addSlash` ([link](https://github.com/ire4ever1190/dimscmd/blob/2a50625e6968d7ba8dcf88d3bb9dca5ec99e4676/src/dimscmd.nim#L233)) doesn't provide argument for description.

## Steps to reproduce
From example of dimscmd provides the code: `cmd.addSlash("add") do (a: int, b: int):`

## Expected behavior
we should be able to add argument for description or make description is not required.

## Screenshots
![image](https://user-images.githubusercontent.com/19174234/119950615-00aa4f00-bfd6-11eb-8934-8252faa2691c.png)

## Additional context
Maybe am I missing something or I have to provide description via parameters? Sorry if I didn't understand it correctly.

**Comment by ire4ever1190** [comment]
Best bug report I've every gotten! thank you for taking the time to get all the info (Might turn this into an issue template)
But basically the description for chat/slash commands is added with doc comments which are like comments except you use two pound signs instead of one (## vs #)
```nim
cmd.addSlash("test") do ():
    ## This is the description
    doStuff()
```

**Comment by rikusen0335** [comment]
Ohhhhh is that description? I didn't know that, thanks!

**Comment by ire4ever1190** [comment]
The description requirement is a bit annoying but is required by discord

**Comment by krisppurg** [comment]
> The description requirement is a bit annoying but is required by discord

Maybe your library could either make an error message saying that you either need to provide a comment?

**Comment by ire4ever1190** [comment]
it provides the assertion defect but I guess that isn't clear that you need to provide a doc comment
I think I can attach an error directly to the addSlash line with some ast manipulation 🤔
