### ISSUE TITLE
Add dynamic & multiple prefixes support

### ISSUE THREAD

**Issue by williamhatcher** [ire4ever1190/dimscmd#2]
discord.py allows you to specify a list or callable (which returns a list) for the prefix and I'd like to add that.

**Comment by ire4ever1190** [comment]
Sorry about this, I went ahead and [implemented it myself](https://github.com/ire4ever1190/dimscmd/commit/8ff72437ad380485dd7db8b2b25a7cd52593fa25). Is it what you were looking for?
