### ISSUE TITLE
User and Role arguments do not work, only some IDs are counted as valid

### ISSUE THREAD

**Issue by sharflare** [ire4ever1190/dimscmd#32]
Describe the bug
When using the "User" and "Role" message command arguments, some pings/IDs are counted as valid while others arent
<user_id> is not a proper userID

Steps to reproduce
use the "User" or "Role" command arguments

Expected behavior
the command to accept the arg

Additional Context
![image](https://github.com/user-attachments/assets/36e24672-9045-4782-9231-541d428c9953)

**Comment by ire4ever1190** [comment]
Closed by #33

**Comment by ire4ever1190** [comment]
Note to self: update tests and somehow make a way for them to run in PRs
