### ISSUE TITLE
Help message for normal commands

### ISSUE THREAD

**Issue by ire4ever1190** [ire4ever1190/dimscmd#4]
Currently I have a proc which generates a help message but it's unused

Biggest issue is coming up with a nice layout so it looks good. Will most likely copy how other libs do it

**Comment by krisppurg** [comment]
It should actually be a tuple of command name and description, args, etc. Maybe even permissions.

**Comment by ire4ever1190** [comment]
Have a basic help message which is good enough for now
Need to work on pagination for it though (and making it not look terrible (and adding in types))
![image](https://user-images.githubusercontent.com/19339842/115027136-ad3cdf80-9f06-11eb-9685-cd01dd3e5347.png)
